version: '2'
services:
    minano-app:
        image: minano
        external_links:
            - minano-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/minano
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    minano-postgresql:
        extends:
            file: postgresql.yml
            service: minano-postgresql
